src/main/java/com/course/malik/model/Mte.java
package com.course.malik.model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "mte")
public class Mte {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_MTE")
    private int mteId;

    @Column(name = "title")
    private String title;

    @Column(name = "phone_number")
    private String phoneNumber;

    @Column(name = "address")
    private String address;

    @ManyToOne
    @JoinColumn(name = "id_City", nullable = false)
    private City mteCity;

    @OneToMany(mappedBy = "driverMte", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Driver> drivers = new HashSet<>();

    @OneToMany(mappedBy = "busMte", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Bus> buses = new HashSet<>();

    public Mte(String title, String phoneNumber, String address, City city) {
        this.title = title;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.mteCity = city;
    }

    public Mte() {
        mteCity = new City();
    }

    public int getMteId() {
        return mteId;
    }

    public City getMteCity() {
        return mteCity;
    }

    public void setMteCity(City mteCity) {
        this.mteCity = mteCity;
    }

    public void setMteId(int mteId) {
        this.mteId = mteId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set<Driver> getDrivers() {
        return drivers;
    }

    public void setDrivers(Set<Driver> drivers) {
        this.drivers = drivers;
    }

    public Set<Bus> getBuses() {
        return buses;
    }

    public void setBuses(Set<Bus> buses) {
        this.buses = buses;
    }

    public int getCityId() {
        return mteCity.getCityId();
    }

    public void setCityId(int idCity) {
        mteCity.setCityId(idCity);
    }

    @Override
    public String toString() {
        return "Mte{" +
                "mteId=" + mteId +
                ", title='" + title + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", address='" + address + '\'' +
                ", city=" + mteCity.getName() +
                '}';
    }
}

src/main/java/com/course/malik/model/SearchingModel.java
package com.course.malik.model;

import org.springframework.stereotype.Component;

import java.sql.Date;
import java.sql.Time;

@Component
public class SearchingModel {

    private int idTrip;

    private WayModel wayModel;

    private Time journeyTime;

    private double price;

    private Date journeyDate;

    public Date getJourneyDate() {
        return journeyDate;
    }

    public void setJourneyDate(Date journeyDate) {
        this.journeyDate = journeyDate;
    }

    public SearchingModel(int idTrip, WayModel wayModel, Time journeyTime, double price) {
        this.idTrip = idTrip;
        this.wayModel = wayModel;
        this.journeyTime = journeyTime;
        this.price = price;
    }

    public SearchingModel() {
    }

    public String getEditJourneyTime() {
        String hstr, mstr;
        int hours = journeyTime.getHours();
        int minutes  = journeyTime.getMinutes();
        if (hours != 0)
            hstr = hours + " ч. ";
        else hstr = "";
        if(minutes != 0)
            mstr = minutes + " м.";
        else mstr = "";
        return hstr + mstr;
    }

    public int getIdTrip() {
        return idTrip;
    }

    public void setIdTrip(int idTrip) {
        this.idTrip = idTrip;
    }

    public WayModel getWayModel() {
        return wayModel;
    }

    public void setWayModel(WayModel wayModel) {
        this.wayModel = wayModel;
    }

    public Time getJourneyTime() {
        return journeyTime;
    }

    public void setJourneyTime(Time journeyTime) {
        this.journeyTime = journeyTime;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
}

src/main/java/com/course/malik/controller/AuthorizationController.java
package com.course.malik.controller;

import com.course.malik.dao.CityDao;
import com.course.malik.dao.UserAccDao;
import com.course.malik.model.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import javax.persistence.NoResultException;
import java.util.List;

@Controller
public class AuthorizationController {

    @Autowired
    private UserAccDao userAccDao;
    @Autowired
    private CityDao cityDao;

    @RequestMapping(value = "/authorization")
    public ModelAndView goAuth() {
        ModelAndView modelAndView = new ModelAndView("user/Authorization");
        modelAndView.addObject("credentials", new Credentials());
        return modelAndView;
    }

    @RequestMapping(value = "/registration")
    public ModelAndView goRegistr() {
        ModelAndView modelAndView = new ModelAndView("user/Registration");
        modelAndView.addObject("user", new UserAccaunt());
        return modelAndView;
    }

    @RequestMapping(value = "saveUser")
    public ModelAndView saveUser(@ModelAttribute UserAccaunt user) {
        UserRole role = new UserRole();
        role.setRoleId(1);
        user.setRole(role);
        userAccDao.save(user);
        return new ModelAndView("redirect: /");
    }

    @RequestMapping(value = "/check", method = RequestMethod.POST)
    public ModelAndView check(@ModelAttribute Credentials credentials) {
        ModelAndView modelAndView;
        UserAccaunt user;
        List<City> cities = cityDao.findAll();
        try {
            user = userAccDao.findUserByEmailAndPassword(credentials.getEmail(), credentials.getPassword());
            if (user == null) throw new Exception();
        }
        catch (Exception ex) {
            ModelAndView model = new ModelAndView("user/ErrorAuth");
            model.addObject("credentials", new Credentials());
            return model;
        }
            if (user.getRole().getRoleId() == 2) {
                ModelAndView model = new ModelAndView("admin/AdminIndexTest");
                model.addObject("cities", cities);
                return model;
            }
            else {
                ModelAndView model = new ModelAndView("index");
                model.addObject("allCities", cities);
                return model;
            }
    }

}

src/main/webapp/WEB-INF/views/user/Authorization.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/auth.css'>
    <title>Authorization</title>
</head>
<body>
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="${pageContext.request.contextPath}/imgs/avatar.png" />
        <p id="profile-name" class="profile-name-card"></p>
        <form:form action="${pageContext.request.contextPath}/check" method="post" class="form-signin" modelAttribute="credentials">
            <span id="reauth-email" class="reauth-email"></span>
            <form:input path="email"  type="email" id="inputEmail" class="form-control" placeholder="Email address" required="true"/>
            <form:input path="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="true"/>
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
        </form:form>
        <a href="${pageContext.request.contextPath}/" class="forgot-password">Return back?</a>
        <br/>
        <a href="${pageContext.request.contextPath}/registration" class="forgot-password">New user? Register!</a>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/user/ErrorAuth.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/auth.css'>
    <title>Authorization</title>
</head>
<body>
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="${pageContext.request.contextPath}/imgs/avatar.png" />
        <p id="profile-name" class="profile-name-card"></p>
        <div class="alert alert-danger">
            <strong>Error with sign in!</strong> Wrong password or email. Try again.
        </div>
        <form:form action="${pageContext.request.contextPath}/check" method="post" class="form-signin" modelAttribute="credentials">
            <span id="reauth-email" class="reauth-email"></span>
            <form:input path="email"  type="email" id="inputEmail" class="form-control" placeholder="Email address" required="true"/>
            <form:input path="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="true"/>
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
        </form:form>
        <a href="${pageContext.request.contextPath}/" class="forgot-password">Return back?</a>
        <br/>
        <a href="${pageContext.request.contextPath}/registration" class="forgot-password">New user? Register!</a>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/user/Registration.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/auth.css'>
    <title>Registration</title>
</head>
<body>
<div class="container">
    <div class="card card-container">
        <form:form action="saveUser" method="post" class="form-signin" role="form" modelAttribute="user">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <form:input path="firstName" type="text" name="first_name" id="first_name" class="form-control" placeholder="First Name" required="true"/>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <form:input path="lastName" type="text" name="last_name" id="last_name" class="form-control" placeholder="Last Name" required="true"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <form:input path="phoneNumber" type="text" name="phone" id="phone" class="form-control" placeholder="Phone number" required="true"/>
            </div>

            <div class="form-group">
                <form:input path="email" type="email" name="email" id="email" class="form-control" placeholder="Email Address" required="true"/>
            </div>

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <form:input path="password" type="password" name="password" id="password" class="form-control" placeholder="Password" required="true"/>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Confirm Password" required>
                    </div>
                </div>
            </div>
            <input type="submit" value="Register" class="btn btn-lg btn-primary btn-block btn-signin">
        </form:form>
        <a href="${pageContext.request.contextPath}/" class="forgot-password">Return to start page?</a>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/views/user/ResultTimetable.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri = "http://www.springframework.org/tags/form" prefix = "form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <title>Расписание</title>
</head>
<body>
<h2>${station.stationName} <br/>
    ${station.stationCity.name} <br/>
    ${station.address} <br/>
</h2>
</body>
</html>

src/main/webapp/WEB-INF/views/user/Timetable.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri = "http://www.springframework.org/tags/form" prefix = "form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <title>Просмотреть расписание</title>
</head>
<body>
<nav class="navbar navbar-default  navbar-fixed" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="submit" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="${pageContext.request.contextPath}/"><img src="${pageContext.request.contextPath}/imgs/logo2.png" width="133" height="30"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="${pageContext.request.contextPath}/carriers"> Перевозчикам </a> </li>
                <li><a href="${pageContext.request.contextPath}/agents"> Агентам </a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="${pageContext.request.contextPath}/authorization"><i class="glyphicon glyphicon-user"></i>&nbspКабинет</a></li>
                <li><a href="#"> <i class="glyphicon glyphicon-calendar"></i>&nbspРасписание</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-info-sign"></i>&nbspСлужба поддержки <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="glyphicon glyphicon-earphone"></i>&nbsp+38 (073) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (097) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (095) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (063) 65-013-01</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>&nbsp&nbsp&nbsp&nbsp&nbspdertalius@gmail.com </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div>
        <div>
            <form action="${pageContext.request.contextPath}/timetable" method="get">
                <div class="form-group row">
                    <div class="col-xs-4">
                        <select class="form-control" name="from">
                            <c:forEach var="stn" items="${stations}" varStatus="status">
                                <option value="${stn.stationId}">${stn.stationName} (${stn.stationCity.name})</option>
                            </c:forEach>
                        </select>
                        <div><h5 style="color:#EAEDF1"> Выберите станцию</h5></div>
                    </div>
                    <div class="searchForm_group form-group">
                        <input type="submit" class="btn btn-default" value="Найти расписание">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/views/user/passem.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<h2>PASS ${pass}</h2>
<h2>EMAIL ${email}</h2>

</body>
</html>

src/main/webapp/WEB-INF/views/user/resultPage.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib uri = "http://www.springframework.org/tags/form" prefix = "form"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/bootstrap.min.css'>
    <link rel='stylesheet' href='${pageContext.request.contextPath}/bootstrap/css/myfooter.css'>
    <title>Bus logic - продажа автобусных билетов по всей Украине</title>
</head>
<body>
<nav class="navbar navbar-default  navbar-fixed" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="submit" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="${pageContext.request.contextPath}/"><img src="${pageContext.request.contextPath}/imgs/logo2.png" width="133" height="30"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#"> Перевозчикам </a> </li>
                <li><a href="#"> Агентам </a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="${pageContext.request.contextPath}/authorization"><i class="glyphicon glyphicon-user"></i>&nbspКабинет</a></li>
                <li><a href="${pageContext.request.contextPath}/admin"> <i class="glyphicon glyphicon-calendar"></i>&nbspРасписание</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-info-sign"></i>&nbspСлужба поддержки <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="glyphicon glyphicon-earphone"></i>&nbsp+38 (073) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (097) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (095) 65-013-01</a></li>
                        <li><a href="#">&nbsp&nbsp&nbsp&nbsp&nbsp+38 (063) 65-013-01</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>&nbsp&nbsp&nbsp&nbsp&nbspdertalius@gmail.com </a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="well" style="background-image: url(${pageContext.request.contextPath}/imgs/bg.jpg); height: 70px;">
    <div >
        <div class="container">
            <div>
                <div>
                    <form action="${pageContext.request.contextPath}/result" method="get">
                        <div class="form-group row">
                            <div class="col-xs-4">
                                <select class="form-control" name="from">
                                    <c:forEach var="city" items="${cities}" varStatus="status">
                                        <option value="${city.cityId}">${city.name}</option>
                                    </c:forEach>
                                </select>
                            </div>
                            <div class="col-xs-4">
                                <select class="form-control" name="to">
                                    <c:forEach var="city" items="${cities}" varStatus="status">
                                        <option value="${city.cityId}">${city.name}</option>
                                    </c:forEach>
                                </select>
                            </div>
                            <div class="col-xs-2">
                                <div>
                                    <input class="form-control" autocomplete="off" id="date" name="date" placeholder="date"  type="text" required/>
                                </div>
                            </div>
                            <div class="searchForm_group form-group">
                                <input type="submit" class="btn btn-default" value="Расписание и цены">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-info center-block">
    <h3 align="center">Выберите подходящий рейс из найденных </h3>
</div>
<div class="row center-block" >
    <div class="col-sm-9">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <div id="dataTable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-4 col-md-4 col-lg-4">
                            </div>
                            <div class="col-sm-4 col-md-4 col-lg-4">
                            </div>
                        </div>
                        <div class="row center-block" >
                            <div class="col-sm-12 center-block">
                                <table class="table table-bordered dataTable center-block" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                    <tr role="row">
                                        <th  tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 400px;">Отправление</th>
                                        <th  tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"  style="width: 400px;">Прибытие</th>
                                        <th  tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 150px;">В пути</th>
                                        <th  tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"  style="width: 150px;">Цена</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <c:forEach var="searched" items="${searchingModels}" >
                                        <tr>
                                            <td>${searched.wayModel.routeWithStartStation.stationOnRoute.stationName} - ${searched.wayModel.routeWithStartStation.stationOnRoute.address} <br/>
                                                <strong>${searched.wayModel.routeWithStartStation.depatureTime}</strong>
                                            </td>
                                            <td>${searched.wayModel.routeWithEndStation.stationOnRoute.stationName} - ${searched.wayModel.routeWithStartStation.stationOnRoute.address} <br>
                                                <strong>${searched.wayModel.routeWithEndStation.arrivalTime}</strong>
                                            </td>
                                            <td> <strong>${searched.editJourneyTime} </strong></td>
                                            <td><a href="${pageContext.request.contextPath}/resulted?start=${searched.wayModel.routeWithStartStation.routeId}&jdate=${jDate}" class="btn btn-primary btn-sm ">Купить за ${searched.price} грн </a></td>
                                        </tr>
                                    </c:forEach>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer-bs">
    <div class="row">
        <div class="col-md-3 footer-brand animated fadeInLeft">
            <a class="navbar-brand"  href="/"><img src="${pageContext.request.contextPath}/imgs/logo2.png" width="133" height="30"></a>
            <p>Suspendisse hendrerit tellus laoreet luctus pharetra. Aliquam porttitor vitae orci nec ultricies. Curabitur vehicula, libero eget faucibus faucibus, purus erat eleifend enim, porta pellentesque ex mi ut sem.</p>
            <p>© 2017 BS3 UI Kit, All rights reserved</p>
        </div>
        <div class="col-md-4 footer-nav animated fadeInUp">
            <h4>Menu —</h4>
            <div class="col-md-6">
                <ul class="pages">
                    <li><a href="#">Travel</a></li>
                    <li><a href="#">Nature</a></li>
                    <li><a href="#">Explores</a></li>
                    <li><a href="#">Science</a></li>
                    <li><a href="#">Advice</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contacts</a></li>
                    <li><a href="#">Terms & Condition</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-2 footer-social animated fadeInDown">
            <h4>Follow Us</h4>
            <ul>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Instagram</a></li>
                <li><a href="#">RSS</a></li>
            </ul>
        </div>
        <div class="col-md-3 footer-ns animated fadeInRight">
            <h4>Отзыв</h4>
            <p>Оставьте свой отзыв</p>
            <p>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                      </span>
            </div>
            </p>
        </div>
    </div>
</footer>

<script type="text/javascript" src="${pageContext.request.contextPath}/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
<script>
    $(document).ready(function(){
        var date_input=$('input[name="date"]'); //our date input has the name "date"
        var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
        date_input.datepicker({
            format: 'mm/dd/yyyy',
            container: container,
            startDate: '+0d',
            todayHighlight: true,
            autoclose: true
        })
    })
</script>
</body>
</html>